# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9831cda3340dcffecbd8a10b5c7fca586bea682f5743f489dd9cabe658cc2a1782f8d6dfcf4a42ea82b80d2492f0398077799f55451839703551c47eaa0de257

test:
  secret_key_base: 21b3f39f9834ec83089de43da1f3cc8e347aadc73938c8af4e1e096ebbf469dedb378ea0f3b676b30774732ae4cb07551cc31e6f11294fb3e27f6c7f01ebe8b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
